apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: express-cert
  namespace: default
spec:
  dnsNames:
    - <Your Domain>
  secretName: ex-ingress-cert500
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
