apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  dnsNames:
    - <Your Domain>
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
